<a href="https://colab.research.google.com/github/dhyan95/Data-Analyst-Project-Sapota-Price-Analysis-and-Calculus-Fundamentals/blob/main/Python_journal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

12/12/25 - Basics of Python

In [2]:
#First day - Pg.65 - 100
#tuple is an immutable, fixed length sequence
tup = (4,5,6,'string')
tup

(4, 5, 6, 'string')

In [3]:
tup1 = tuple('string')
tup1

('s', 't', 'r', 'i', 'n', 'g')

In [4]:
nested_tuple = (4,5,6),(8,9)
nested_tuple[1]

(8, 9)

In [5]:
#lists are mutable and variable length sequence
list1 = ["lists"]
list1

['lists']

In [6]:
list1.append("dwarf")
list1

['lists', 'dwarf']

In [7]:
list1.insert(0,'hello')
list1

['hello', 'lists', 'dwarf']

In [8]:
list1.pop(2)
list1

['hello', 'lists']

In [9]:
list1.remove("lists")
list1

['hello']

In [10]:
"hello" in list1 #can also use not in

True

In [11]:
#concatenating and combining
[4,None,"foo"]+[1,2,3]

[4, None, 'foo', 1, 2, 3]

In [12]:
#sorting
a=[7,4,5,2]
a.sort()  #for characters use sort(key=len)
a

[2, 4, 5, 7]

In [13]:
#slicing
seq = (3,4,5,6,7,3,1,2,4,7,8)
seq[1:5]  #seq[:5];seq[3:]

(4, 5, 6, 7)

In [14]:
#reversing a tuple
reversed_seq = seq[::-1]
reversed_seq

(8, 7, 4, 2, 1, 3, 7, 6, 5, 4, 3)

In [15]:
#dictionary - it stores key value pairs use this instead of hashmaps?
d1 = {"a":"hello","b":[1,2,3]}
d1
#for inserting,accessing,setting same as tuple or list
#del for delete
#update for appending

{'a': 'hello', 'b': [1, 2, 3]}

In [16]:
#set is an unordered collection of unique elements
a={1,2,3,1,2,3}
a

{1, 2, 3}

In [17]:
a1 = {1,2,3,4}
b1 = {3,4,5,6}
#union function
a1.union(b1) #a1 | b1

{1, 2, 3, 4, 5, 6}

In [18]:
#intersection
a1.intersection(b1) #a1 & b1
#refer table 3.1 page 78

{3, 4}

In [19]:
#built in sequence functions

#sorted([3,2,1]) function
#reversed() function

In [20]:
#functions
def func():
  return "greet"
print(func())

greet


In [21]:
def profile(name,age):
  print(name,age)
profile(name="Dhyan",age=21)

Dhyan 21


In [22]:
#for loop
fruits = ['apple','banana','mango']
for f in fruits:
  print(f,len(f))

apple 5
banana 6
mango 5


In [23]:
#looping through a dictionary
student = {"name":"dhyan","age":21}
for key,value in student.items():
  print(key,":",value)

name : dhyan
age : 21


In [24]:
count = 1
while count <= 5:
  print(count)
  count+=1

1
2
3
4
5


In [25]:
#sum of a list using a function and loop
listt = [2,3,3,5,6]
def sum_list():
  sum = 0
  for i in listt:
    sum+=i
  return sum
print(sum_list())

19


In [26]:
#remove duplicates from a list - convert it to set
con_set = set(listt)
print(con_set)

{2, 3, 5, 6}


In [27]:
#word counter
list_word = ["Hello","How","Are","You"]
def word_counter():
  count = 0
  for l in list_word:
    count+=1
  return count
print(word_counter())

4


EDGE QUESTIONS

In [28]:
if 0.2+0.3==0.5:
  print("true")
else:
  print("false")

true


In [29]:
print("/\\/\\/\\")

/\/\/\


12/13/25 NUMPY - https://numpy.org/devdocs/user/absolute_beginners.html#

In [30]:
import numpy as np
arr = np.array(range(0,10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr.dtype

dtype('int64')

In [32]:
arr1 = np.array([(1,2,3),(4,5,6),(7,8,9)])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
np.arange(10,30,5)   #np.arange(10,30)

array([10, 15, 20, 25])

In [34]:
np.zeros((3,4,7))   #np.ones((3,4,7)) as the name suggests

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [35]:
np.linspace(10,30,5)  #for float numbers

array([10., 15., 20., 25., 30.])

ADDING, REMOVING AND SORTING

In [36]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

In [37]:
np.delete(x,1)

array([1, 3])

How to convert a 1D array into a 2D array

In [38]:
x.shape

(3,)

In [39]:
x1 = x[np.newaxis, :]  #for column vector [:, np.newaxis]
x1.shape

(1, 3)

BASIC OPERATIONS

In [40]:
a = np.random.rand(2,2)
a

array([[0.52714591, 0.09336255],
       [0.29080724, 0.71295511]])

In [41]:
b = np.array([(1,2),(3,4)])
b

array([[1, 2],
       [3, 4]])

In [42]:
#addition
c = a+b
c

array([[1.52714591, 2.09336255],
       [3.29080724, 4.71295511]])

In [43]:
#sqaure
b**2

array([[ 1,  4],
       [ 9, 16]])

In [44]:
#matrix multiplication
a@b

array([[0.80723356, 1.42774202],
       [2.42967257, 3.43343492]])

In [45]:
a<0.1

array([[False,  True],
       [False, False]])

INDEXING, SLICING, ITERATING

In [46]:
arr[5]

np.int64(5)

In [47]:
arr[3:5]

array([3, 4])

In [48]:
#reversed
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [49]:
arr[::3] #first colon means beginning of the array, the second means end of the array and the number 3 is the step value

array([0, 3, 6, 9])

VSTACK, HSTACK

In [50]:
a1 = np.array([(1,2,3),(4,5,6)])
a2 = np.array([(7,8,9),(10,11,12)])

In [51]:
np.concatenate((a1,a2),axis=1)  #for vstack axis=0

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [52]:
np.vstack((a1,a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
np.hstack((a1,a2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

BROADCASTING - operations on arrays of different sizes

In [54]:
x1*1.6

array([[1.6, 3.2, 4.8]])

Reshaping and flattening multidimensional arrays

In [55]:
x

array([1, 2, 3])

In [56]:
a1 = x.flatten()  #changes to new array wont affect the parent array
a1

array([1, 2, 3])

In [57]:
a1.ravel() #opposite of flatten

array([1, 2, 3])

CALCULUS / STATISTICS FUNCTIONS

In [58]:
a10 = 2*np.random.rand(1000) + 10
a10

array([10.50643455, 11.76554723, 10.03691828, 10.24200257, 10.85973146,
       10.11971382, 10.33953061, 10.53874672, 10.45674898, 10.47822653,
       10.98022419, 11.50585098, 10.66210297, 11.24952887, 11.87649862,
       11.77062776, 11.38278786, 11.87154154, 11.74546813, 10.01979124,
       10.41661274, 10.71005668, 10.90467909, 11.40098258, 10.75210789,
       11.20613004, 11.35511503, 11.68045794, 11.6793302 , 10.09935418,
       11.46899309, 11.64950635, 10.18571355, 10.99533954, 10.01410275,
       11.65999885, 10.99835601, 10.44585855, 11.8623237 , 10.60768327,
       11.26942597, 10.7278329 , 10.46483889, 11.54538148, 11.20440175,
       11.18318727, 10.50351688, 10.11378526, 11.63868095, 11.25924219,
       11.74314528, 10.64476858, 11.83415818, 10.00885901, 11.52165813,
       11.41239133, 10.50054778, 11.88992344, 10.71652477, 11.12144489,
       11.3458342 , 10.07591479, 11.29024638, 10.24115246, 11.09258309,
       11.52195584, 11.59005464, 10.24399799, 11.93817394, 11.31

In [59]:
np.mean(a10)

np.float64(10.99702905820696)

In [60]:
np.std(a10)

np.float64(0.5768900104509946)

In [61]:
np.percentile(a10,80)  #80% of numbers are less than 11.62

np.float64(11.598463740722687)

In [62]:
import numpy as np

a = np.arange(10)
b = a[2:8]
b[:] = -1

print(a)

[ 0  1 -1 -1 -1 -1 -1 -1  8  9]


Sales Data Analysis
You have daily sales data for a small store for a month (30 days) stored as a list:

In [63]:
sales = [200, 220, 250, 180, 210, 240, 230, 260, 200, 190, 220, 210, 250, 270, 300, 310, 290, 280, 260, 270, 300, 320, 310, 300, 290, 280, 270, 260, 250, 240]

#Convert this list into a NumPy array.
sales_arr = np.array(sales)
print("Sales Array:", sales_arr)

#Compute the average sales, maximum sales, and minimum sales.
print("Average sales:", np.average(sales_arr))
print("Maximum sales:", np.max(sales_arr))
print("Minimum sales:", np.min(sales_arr))

#Find the days when sales exceeded 280.
high_sales_days = sales_arr[sales_arr > 280]
print('Sales that exceeded 280:', high_sales_days)

Sales Array: [200 220 250 180 210 240 230 260 200 190 220 210 250 270 300 310 290 280
 260 270 300 320 310 300 290 280 270 260 250 240]
Average sales: 255.33333333333334
Maximum sales: 320
Minimum sales: 180
Sales that exceeded 280: [300 310 290 300 320 310 300 290]


Temperature Monitoring
A city records hourly temperatures in Celsius over a week (7 days × 24 hours = 168 readings) as a NumPy array called temps.

In [64]:
#Convert the temperatures to Fahrenheit.
temps_cel = np.random.rand(168) + 30
temps_cel

temps_fah = (temps_cel - 30)*2
temps_fah

#Identify the coldest day and the hottest day based on daily averages.
print("Coldest day in fahrenheit, my arse is freezing: ",np.min(temps_fah))
print("Hottest day in fahrenheit: ",np.max(temps_fah))

#Find all hours when the temperature was below 0°C.
below = temps_fah[temps_fah<0.6]
print("Hours when the temperature was below 0°C: ",below)

Coldest day in fahrenheit, my arse is freezing:  0.0017467957753822816
Hottest day in fahrenheit:  1.9999149637257503
Hours when the temperature was below 0°C:  [0.41686338 0.5457619  0.10975107 0.477049   0.46079425 0.07890353
 0.1809999  0.28106146 0.0017468  0.54705746 0.49661437 0.40000878
 0.52346626 0.139048   0.59326315 0.2281738  0.12681349 0.38418281
 0.45624583 0.49599972 0.13628208 0.36868028 0.42193367 0.17015449
 0.50027857 0.19452312 0.11489638 0.08269755 0.26203222 0.43094434
 0.52221239 0.1058702  0.56990838 0.13757759 0.18862769 0.57518929
 0.45334017 0.46878289 0.53743071 0.30343059 0.1033183  0.32516562
 0.38123609 0.07479952 0.38158318 0.38310786 0.53210105 0.08274287
 0.21952432 0.56441939 0.36784843 0.52709933 0.32284748 0.34800937]


Class Grades
You have grades for 5 students in 4 subjects as a NumPy array:

In [65]:
grades = np.array([
 [85, 90, 78, 92],
 [70, 75, 80, 72],
 [88, 82, 91, 85],
 [60, 65, 58, 62],
 [95, 92, 88, 96]
])

#Compute each student’s average grade.
student1_average = np.average(grades[0])
print("Student 1: ",student1_average)
student2_average = np.average(grades[1])
print("Student 2: ",student2_average)
student3_average = np.average(grades[2])
print("Student 3: ",student3_average)
student4_average = np.average(grades[3])
print("Student 4: ",student4_average)

#Find the subject with the highest average score.
subject1_average = np.average(grades[:,0])
print("Subject 1: ",subject1_average)

#Identify students scoring above 90 in at least 2 subjects.
above_90_counts = np.sum(grades > 90, axis=1)
students_above_90 = np.where(above_90_counts >= 2)[0]
print("Students scoring above 90 in at least 2 subjects:", students_above_90)

Student 1:  86.25
Student 2:  74.25
Student 3:  86.5
Student 4:  61.25
Subject 1:  79.6
Students scoring above 90 in at least 2 subjects: [4]


FOCUS ON VECTORS

1) Temperature Alerts

In [66]:
temp = np.random.rand(365,24) + 30
temp

#Identify all days where the temperature exceeded 35°C for more than 5 hours.
hot_hours = temp>30.9
hot_hours_count = np.sum(hot_hours,axis=1)
hot_days = np.where(hot_hours_count>5)[0]
hot_days

array([ 46,  67, 111, 154, 163, 181, 199, 244, 286, 332])

2) Sales Performance

In [67]:
sale = np.random.rand(12,6) + (3000-1000)
sale

#Find products whose average quarterly sales exceeded 500.
quaterly = sale/4
quaterly
product_qua = np.where(np.average(quaterly,axis=0)>500.123)[0]
product_qua

#Identify months where all products had sales above 2000.
all_products = np.all(sale>2000,axis=0)
all_products

array([ True,  True,  True,  True,  True,  True])

3) Exam Score Analysis

In [68]:
scores = np.random.rand(10,5) + 80    #students vs subjects
scores

#Identify students who scored above 80 in all subjects.
top_students = np.where(np.all(scores > 80, axis=1))[0]
top_students

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

12/15/25 - LINEAR ALGEBRA WITH NumPy and SciPy

Dot product - same as inner product

In [69]:
import numpy as np
np.dot([3j+0,5j+2],[2j+5,1j+2])

np.complex128(-7+27j)

Vdot - same syntax as dot, unlike dot it flattens the array into a 1D array and then performs the operations.
Not as powerful as vecdot

Multi Dot

In [70]:
from numpy.linalg import multi_dot
A = np.random.rand(100,100)
B = np.random.rand(100,10)
C = np.random.rand(10,100)
multi_dot([A,B,C])

array([[101.97988361, 134.31211253, 140.50757126, ..., 129.40432799,
        159.58443438, 157.20431881],
       [100.96594265, 131.61394837, 141.29095579, ..., 128.44785885,
        158.20257605, 154.95745979],
       [104.34737576, 136.70014762, 143.62266913, ..., 132.43727823,
        161.39141295, 160.23872816],
       ...,
       [103.44500827, 134.25387137, 142.91557131, ..., 131.16120076,
        160.74769365, 157.36924848],
       [ 95.94754683, 124.20078278, 132.70868988, ..., 122.43673946,
        148.71706105, 145.46577215],
       [ 97.41530422, 127.32517027, 133.4558044 , ..., 123.22988253,
        152.81768132, 150.6588833 ]])

VecDot - working with multiple arrays and when one wants to use broadcasting functions on arrays. Very similar to linalg.vecdot - for specifying explicitly that this is a linear algebra function

In [71]:
v = np.array([(0., 5., 0.), [0., 0., 10.], [0., 6., 8.]])
n = np.array([0., 0.6, 0.8])
np.vecdot(v, n)

array([ 3.,  8., 10.])

Tensor dot

In [72]:
a_0 = np.array([[1, 2], [3, 4]])
b_0 = np.array([[5, 6], [7, 8]])
c_0 = np.tensordot(a_0,b_0,axes=0)
c_0

array([[[[ 5,  6],
         [ 7,  8]],

        [[10, 12],
         [14, 16]]],


       [[[15, 18],
         [21, 24]],

        [[20, 24],
         [28, 32]]]])

In [1]:
print("Hello")

Hello
